### ISSUE TITLE
Abort at Florist Friar's Cottage following Crackpot Mystic choices.

### ISSUE THREAD

**Issue by capncastom** [Kasekopf/loopsmol#28]
Hi!

I've notice that more often than not, loopsmol will abort following the Crackpot Mystic choices, and getting itself stuck in the Florist Friar's cottage:

```
Executing Digital/Open [Route]

Executing Digital/Open
Autoattack is disabled.

Talking to the Crackpot Mystic
Preference _concoctionDatabaseRefreshes changed from 73 to 74
Submitting option 1 for choice 664
Submitting option 1 for choice 664
Submitting option 1 for choice 0
Unsupported choice adventure #720
Unexpected error, debug log printed.
Preference floristFriarChecked changed from false to true
Preference floristFriarAvailable changed from false to true
choice 3: (secret choice)
[Click here to continue in the relay browser.](http://127.0.0.1:60080/game.php)

logPreferenceChange => false
Preference logPreferenceChange changed from true to false
logPreferenceChangeFilter => spadingData,combo_lastTileCombed,_beachLayout,_beachMinutes,_beachCombing
hpAutoRecoveryTarget => 0
mpAutoRecoveryTarget => 0
choiceAdventureScript =>
CCS set to grimoire_macro
choiceAdventure1340 => 1
choiceAdventure1468 => 2
choiceAdventure1469 => 3
choiceAdventure1471 => 1
choiceAdventure1472 => 1
choiceAdventure1473 => 1
choiceAdventure1474 => 2
choiceAdventure1475 => 1
JavaScript exception: KoLmafia error: Unexpected error, debug log printed.
at file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/loopsmol/loopsmol.js:12860
at file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/loopsmol/loopsmol.js:10915 (_do)
at file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/loopsmol/loopsmol.js:5924 (execute)
at file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/loopsmol/loopsmol.js:10569 (execute)
at file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/loopsmol/loopsmol.js:5842 (run)
at file:/Users/casey/Library/Application%20Support/KoLmafia/scripts/loopsmol/loopsmol.js:20187 (main)
```

Following the abort, I usually leave the friar dialog and grab the continuum transfunctioner myself in the relay browser, as I assume thats what the script was up to. Re-running following that goes fine.

**Comment by Kasekopf** [comment]
Looking at your log, I didn't realize before but this is actually enough of an error that KoLmafia is printing a debug log as well. Could you share the error in the log as well? It should be in a file like `DEBUG_202402015.txt` (with the date it was generated) in your main KoLmafia folder.

**Comment by capncastom** [comment]
sure, here is the freshest one:


```

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
              KoLmafia r27952, Mac OS X, Java 21.0.1
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 Please note: do not post this log in the KoLmafia thread of KoL's
 Gameplay-Discussion forum. If you would like the KoLmafia dev team
 to look at it, please write a bug report at kolmafia.us. Include
 specific information about what you were doing when you made this
 and include this log as an attachment.
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 Timestamp: Fri May 24 06:45:28 EDT 2024
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 User: capn castom


=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
              KoLmafia r27952, Mac OS X, Java 21.0.1
 Current run: 0=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 Please note: do not post this log in the KoLmafia thread of KoL's
 Gameplay-Discussion forum. If you would like the KoLmafia dev team
 to look at it, please write a bug report at kolmafia.us. Include MRU Script: Unknown

 specific information about what you were doing when you made this=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 and include this log as an attachment.


=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 Timestamp: Fri May 24 06:45:28 EDT 2024
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 User: capn castom
 Current run: 0
 MRU Script: Unknown
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Unexpected error, debug log printed.
Unexpected error, debug log printed.
class java.lang.NullPointerException: Cannot invoke "org.mozilla.javascript.Scriptable.getParentScope()" because "obj" is null
class java.lang.NullPointerException: Cannot invoke "org.mozilla.javascript.Scriptable.getParentScope()" because "obj" is null
java.lang.NullPointerException: Cannot invoke "org.mozilla.javascript.Scriptable.getParentScope()" because "obj" is null
	at org.mozilla.javascript.ScriptableObject.getTopLevelScope(ScriptableObject.java:1941)
	at org.mozilla.javascript.ScriptableObject.getFunctionPrototype(ScriptableObject.java:1888)
	at org.mozilla.javascript.commonjs.module.Require.<init>(Require.java:87)
	at net.sourceforge.kolmafia.textui.javascript.SafeRequire.<init>(SafeRequire.java:30)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.lambda$executeRun$4(JavascriptRuntime.java:353)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.executeFunction(JavascriptRuntime.java:255)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.executeRun(JavascriptRuntime.java:347)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.lambda$execute$1(JavascriptRuntime.java:233)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.execute(JavascriptRuntime.java:232)
	at net.sourceforge.kolmafia.textui.AbstractRuntime.execute(AbstractRuntime.java:24)
	at net.sourceforge.kolmafia.session.SpadingManager.invokeSpadingScript(SpadingManager.java:144)
	at net.sourceforge.kolmafia.session.SpadingManager.processChoiceVisit(SpadingManager.java:70)
	at net.sourceforge.kolmafia.session.ChoiceManager.visitChoice(ChoiceManager.java:2489)
	at net.sourceforge.kolmafia.session.ChoiceManager.postChoice2(ChoiceManager.java:2432)
	at net.sourceforge.kolmafia.request.GenericRequest.processResponse(GenericRequest.java:2240)
	at net.sourceforge.kolmafia.request.GenericRequest.retrieveServerReply(GenericRequest.java:2142)
	at net.sourceforge.kolmafia.request.GenericRequest.retrieveServerReply(GenericRequest.java:1734)
	at net.sourceforge.kolmafia.request.GenericRequest.externalExecute(GenericRequest.java:1400)
	at net.sourceforge.kolmafia.request.GenericRequest.execute(GenericRequest.java:1387)
	at net.sourceforge.kolmafia.request.GenericRequest.run(GenericRequest.java:1153)
	at net.sourceforge.kolmafia.RequestThread.postRequest(RequestThread.java:242)
	at net.sourceforge.kolmafia.RequestThread.postRequest(RequestThread.java:207)
	at net.sourceforge.kolmafia.request.FloristRequest.checkFloristAvailable(FloristRequest.java:181)
	at net.sourceforge.kolmafia.textui.RuntimeLibrary.florist_available(RuntimeLibrary.java:10327)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.sourceforge.kolmafia.textui.parsetree.LibraryFunction.execute(LibraryFunction.java:71)
	at net.sourceforge.kolmafia.textui.parsetree.FunctionCall.execute(FunctionCall.java:113)
	at net.sourceforge.kolmafia.textui.parsetree.Operator.applyTo(Operator.java:542)
	at net.sourceforge.kolmafia.textui.parsetree.Operation.execute(Operation.java:73)
	at net.sourceforge.kolmafia.textui.parsetree.Conditional.execute(Conditional.java:41)
	at net.sourceforge.kolmafia.textui.parsetree.If.execute(If.java:35)
	at net.sourceforge.kolmafia.textui.parsetree.BasicScope.execute(BasicScope.java:403)
	at net.sourceforge.kolmafia.textui.parsetree.UserDefinedFunction.execute(UserDefinedFunction.java:87)
	at net.sourceforge.kolmafia.textui.parsetree.FunctionCall.execute(FunctionCall.java:113)
	at net.sourceforge.kolmafia.textui.parsetree.BasicScope.execute(BasicScope.java:403)
	at net.sourceforge.kolmafia.textui.AshRuntime.executeScope(AshRuntime.java:240)
	at net.sourceforge.kolmafia.textui.AshRuntime.execute(AshRuntime.java:190)
	at net.sourceforge.kolmafia.KoLmafiaASH.getClientHTML(KoLmafiaASH.java:143)
	at net.sourceforge.kolmafia.KoLmafiaASH.getClientHTML(KoLmafiaASH.java:111)
	at net.sourceforge.kolmafia.KoLmafiaASH.getClientHTML(KoLmafiaASH.java:85)
	at net.sourceforge.kolmafia.request.RelayRequest.handleSimple(RelayRequest.java:3706)
	at net.sourceforge.kolmafia.request.RelayRequest.run(RelayRequest.java:3733)
	at net.sourceforge.kolmafia.RequestThread.postRequest(RequestThread.java:242)
	at net.sourceforge.kolmafia.RequestThread.postRequest(RequestThread.java:207)
	at net.sourceforge.kolmafia.webui.RelayAgent.readServerResponse(RelayAgent.java:436)
	at net.sourceforge.kolmafia.webui.RelayAgent.performRelay(RelayAgent.java:104)
	at net.sourceforge.kolmafia.webui.RelayAgent.run(RelayAgent.java:83)

java.lang.NullPointerException: Cannot invoke "org.mozilla.javascript.Scriptable.getParentScope()" because "obj" is null
	at org.mozilla.javascript.ScriptableObject.getTopLevelScope(ScriptableObject.java:1941)
	at org.mozilla.javascript.ScriptRuntime.setBuiltinProtoAndParent(ScriptRuntime.java:4271)
	at org.mozilla.javascript.Context.newObject(Context.java:1493)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.lambda$executeRun$4(JavascriptRuntime.java:370)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.executeFunction(JavascriptRuntime.java:255)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.executeRun(JavascriptRuntime.java:347)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.execute(JavascriptRuntime.java:229)
	at net.sourceforge.kolmafia.textui.AbstractRuntime.execute(AbstractRuntime.java:24)
	at net.sourceforge.kolmafia.session.SpadingManager.invokeSpadingScript(SpadingManager.java:144)
	at net.sourceforge.kolmafia.session.SpadingManager.processChoice(SpadingManager.java:75)
	at net.sourceforge.kolmafia.session.ChoiceManager.postChoice2(ChoiceManager.java:2429)
	at net.sourceforge.kolmafia.request.GenericRequest.processResponse(GenericRequest.java:2240)
	at net.sourceforge.kolmafia.request.GenericRequest.retrieveServerReply(GenericRequest.java:2142)
	at net.sourceforge.kolmafia.request.GenericRequest.retrieveServerReply(GenericRequest.java:1734)
	at net.sourceforge.kolmafia.request.GenericRequest.externalExecute(GenericRequest.java:1400)
	at net.sourceforge.kolmafia.request.GenericRequest.execute(GenericRequest.java:1387)
	at net.sourceforge.kolmafia.request.GenericRequest.run(GenericRequest.java:1153)
	at net.sourceforge.kolmafia.session.ChoiceManager.processChoiceAdventure(ChoiceManager.java:210)
	at net.sourceforge.kolmafia.session.ChoiceManager.processRedirectedChoiceAdventure(ChoiceManager.java:131)
	at net.sourceforge.kolmafia.request.GenericRequest.handleServerRedirect(GenericRequest.java:2053)
	at net.sourceforge.kolmafia.request.GenericRequest.retrieveServerReply(GenericRequest.java:1763)
	at net.sourceforge.kolmafia.request.GenericRequest.externalExecute(GenericRequest.java:1400)
	at net.sourceforge.kolmafia.request.GenericRequest.execute(GenericRequest.java:1387)
	at net.sourceforge.kolmafia.request.GenericRequest.run(GenericRequest.java:1153)
	at net.sourceforge.kolmafia.session.ChoiceManager.processChoiceAdventure(ChoiceManager.java:163)
	at net.sourceforge.kolmafia.textui.RuntimeLibrary.run_choice(RuntimeLibrary.java:7330)
	at net.sourceforge.kolmafia.textui.RuntimeLibrary.run_choice(RuntimeLibrary.java:7288)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.sourceforge.kolmafia.textui.parsetree.LibraryFunction.executeWithoutInterpreter(LibraryFunction.java:104)
	at net.sourceforge.kolmafia.textui.javascript.LibraryFunctionStub.execute(LibraryFunctionStub.java:48)
	at net.sourceforge.kolmafia.textui.javascript.AshStub.call(AshStub.java:137)
	at net.sourceforge.kolmafia.textui.javascript.LibraryFunctionStub.call(LibraryFunctionStub.java:100)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1871)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1053)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.lambda$executeRun$4(JavascriptRuntime.java:370)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.executeFunction(JavascriptRuntime.java:255)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.executeRun(JavascriptRuntime.java:347)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.lambda$execute$1(JavascriptRuntime.java:233)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
	at net.sourceforge.kolmafia.textui.javascript.JavascriptRuntime.execute(JavascriptRuntime.java:232)
	at net.sourceforge.kolmafia.textui.AbstractRuntime.execute(AbstractRuntime.java:24)
	at net.sourceforge.kolmafia.textui.command.CallScriptCommand.call(CallScriptCommand.java:196)
	at net.sourceforge.kolmafia.KoLmafiaCLI.doExecuteCommand(KoLmafiaCLI.java:477)
	at net.sourceforge.kolmafia.KoLmafiaCLI.executeCommand(KoLmafiaCLI.java:433)
	at net.sourceforge.kolmafia.KoLmafiaCLI.executeLine(KoLmafiaCLI.java:352)
	at net.sourceforge.kolmafia.KoLmafiaCLI.executeLine(KoLmafiaCLI.java:239)
	at net.sourceforge.kolmafia.swingui.CommandDisplayFrame$CommandQueueHandler.handleQueue(CommandDisplayFrame.java:139)
	at net.sourceforge.kolmafia.swingui.CommandDisplayFrame$CommandQueueHandler.run(CommandDisplayFrame.java:117)

```

**Comment by bigbongobeats** [comment]
I see this same issue as well - not always, but maybe half the time? Can provide logs as requested/useful.
